server:
  port: 8080

spring:
  profiles:
    include: oauth
    active: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://google/donedone-db?cloudSqlInstance=donedone-376207:asia-northeast3&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=1212&useSSL=false

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

jwt:
  secret: donedone
